apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: 
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
           - name: ms-loader-sibel-container
             image: 
             imagePullPolicy: Always
          imagePullSecrets:
           - name: 
          restartPolicy: OnFailure
